# fonte: https://blog.knoldus.com/how-to-build-publish-on-dockerhub-using-github-action/

name: Build and push Docker image to Docker hub

on:
  push:
    branches: [ main ]

jobs:
  deploy:
      name: Setup Gcloud Account
      runs-on: ubuntu-latest
      env:
        IMAGE_NAME: gcr.io/${{ secrets.GCP_ID }}/site:latest
      steps:

        - name: Checkout
          uses: actions/checkout@v2

        - uses: google-github-actions/setup-gcloud@v0.2.0
          with:
            service_account_key: ${{ secrets.GCP_CREDENTIALS }}
            project_id: ${{ secrets.GCP_ID }}

        - name: Configure Docker in GCP
          run: gcloud auth configure-docker --quiet

        - name: Build Docker image
          run: docker build -t $IMAGE_NAME .

        - name: Push Docker image
          run: docker push $IMAGE_NAME

        - name: Deploy Docker image
          run: gcloud run deploy labinventary --image $IMAGE_NAME --region us-central1 --memory 128Mi --min-instances 0 --max-instances 1 --platform managed --port 5000 --allow-unauthenticated --update-env-vars FLASK_RUN_PORT=5000,FLASK_RUN_HOST=0.0.0.0"

  build:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout 
          uses: actions/checkout@v38080
          
        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_PASS }}

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

        - name: Build and push
          uses: docker/build-push-action@v2
          with:
            context: .
            file: ./Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_HUB_USERNAME }}/inventary:latest
